export const ProjectsData = [
  {
    prItem: 1,
    prImg: "https://drive.google.com/uc?export=view&id=19SJUHdxZgfb-2Nj3xUBo5t0aPZy_LpLl",    
    prTitle: "¿Wich one is better?",
    prDescription: "La temática de la página tributo es sobre suspensiones de bicicleta, su tecnología, diseño y funcionamiento. Para ello, se han integrado diferentes apartados gráficos que permiten ver su diseño. Por otra parte se hace un recorrido específico por cada suspensión explicando cuáles son sus tecnologías ofrecidas y por último, se hace una comparativa de precios entre diferentes gamas de cada suspension. Adicionalmente, se ha diseñado un foro en el cual las personas podrán interactuar sobre sus experiencias usando cada suspensión.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://html-web-tributo.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/HTML-WEB-tributo-.git",
  },
  {
    prItem: 2,
    prImg: "https://drive.google.com/uc?export=view&id=1MBk_5GkU3kcOpVbWDxjOD3lWzZX6hoB2",
    prTitle: "Z-Shop",
    prDescription: "Ejercicio de maquetación y corrección de estilo usando las propiedades de CSS FLEXBOX/GRID.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/Z-Shop/",
    prRepoitory: "https://github.com/CrisCaBeRi/Z-Shop.git",
  },
  {
    prItem: 3,
    prImg: "https://drive.google.com/uc?export=view&id=1I6ht_pBxZjJKrhImhF6p79zuBhBlkqI3",
    prTitle: "SabujCha-T",
    prDescription: "Maquetación responsive mobile-first para página web de venta de té",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/SabujCha-T-/",
    prRepoitory: "https://github.com/CrisCaBeRi/SabujCha-T-.git",
  },
  {
    prItem: 4,
    prImg: "https://drive.google.com/uc?export=view&id=1TBG9-XB53qeZVZlcfvTmQhfBnYug4lhP",
    prTitle: "Fundación Semillas",
    prDescription: "Maquetación dashboard ficticio. La Fundación Semillas, que ofrece diplomados en sostenibilidad del medio ambiente, desea saber el estado de ánimo sus alumnos, además de querer suministrarles una herramienta de fácil manejo, donde puedan organizar las tareas diarias propuestas por la institución.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/Semillas_emociones_Y_tareas/",
    prRepoitory: "https://github.com/CrisCaBeRi/Semillas_emociones_Y_tareas.git",
  },
  {
    prItem: 5,
    prImg: "https://drive.google.com/uc?export=view&id=1UZzkeWRhhYx9rvHwTbuIog0RQuk-80op",
    prTitle: "Tetris JS",
    prDescription: "Video juego introductorio a JS." ,
    prTechnologies: ["html", "css", "js"],    
    prDeploy: "https://criscaberi.github.io/Programate_Academy_TETRIS/",
    prRepoitory: "https://github.com/CrisCaBeRi/Programate_Academy_TETRIS.git",
  },
  {
    prItem: 6,
    prImg: "https://drive.google.com/uc?export=view&id=1VkD7YYDZ33HGnBcimmGLlhIfSmgSgNHK",
    prTitle: "Dashboard Crypto",
    prDescription: "Desarrollo forntend usando REACT y haciendo consumo de API sobre criptomonedas.",
    prTechnologies: ["html", "css", "js", "react"],
    prDeploy: "https://criscaberi.github.io/DashboardCrypto/",    
    prRepoitory: "https://github.com/CrisCaBeRi/DashboardCrypto.git"    
  },
  {
    prItem: 7,
    prImg: "https://drive.google.com/uc?export=view&id=11rtV2oqR-eNFX4pW1W-6W0X5QSdex5lv",
    prTitle: "Angel's Makeup",
    prDescription: "Proyecto de tienda virtual para cliente real utilizando REACT.",
    prTechnologies: ["html", "css", "js", "react"],
    prDeploy: "https://angels-make-up.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/angelsMakeUp.git",
  }  
];
