export const ProjectsData = [
  {
    prItem: 1,
    prImg: "https://drive.google.com/uc?export=view&id=19SJUHdxZgfb-2Nj3xUBo5t0aPZy_LpLl",    
    prTitle: "¿Wich one is better?",
    prDescription: "La temática de la página tributo es sobre suspensiones de bicicleta, su tecnología, diseño y funcionamiento. Para ello, se han integrado diferentes apartados gráficos que permiten ver su diseño. Por otra parte, se hace un recorrido específico por cada suspensión explicando cuáles son sus tecnologías ofrecidas y por último, se hace una comparativa de precios entre diferentes gamas de cada suspensión. Adicionalmente, se ha diseñado un foro en el cual las personas podrán interactuar sobre sus experiencias usando cada suspensión.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://html-web-tributo.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/HTML-WEB-tributo-.git",
  },
  {
    prItem: 2,
    prImg: "https://drive.google.com/uc?export=view&id=1MBk_5GkU3kcOpVbWDxjOD3lWzZX6hoB2",
    prTitle: "Z-Shop",
    prDescription: "Ejercicio de corrección de maquetación web y estilos. Por medio de propiedades de CSS como FLEXBOX y GRID se realizan los ajustes correspondientes para mantener el equilibrio visual de la página.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/Z-Shop/",
    prRepoitory: "https://github.com/CrisCaBeRi/Z-Shop.git",
  },
  {
    prItem: 3,
    prImg: "https://drive.google.com/uc?export=view&id=1I6ht_pBxZjJKrhImhF6p79zuBhBlkqI3",
    prTitle: "SabujCha-T",
    prDescription: "Ejercicio de maquetación web con características responsive basado en el diseño mobile-first con tres puntos de quiebre para un ejemplo de página web, tipo landing page, para la venta de té.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/SabujCha-T-/",
    prRepoitory: "https://github.com/CrisCaBeRi/SabujCha-T-.git",
  },
  {
    prItem: 4,
    prImg: "https://drive.google.com/uc?export=view&id=1TBG9-XB53qeZVZlcfvTmQhfBnYug4lhP",
    prTitle: "Fundación Semillas",
    prDescription: "Maquetación de un dashboard ficticio. La Fundación Semillas, que ofrece diplomados en sostenibilidad del medio ambiente, desea saber el estado de ánimo sus alumnos, además de querer suministrarles una herramienta de fácil manejo, donde puedan organizar las tareas diarias propuestas por la institución. En esta maquetación se incluyen principios básicos de animación con CSS.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://criscaberi.github.io/Semillas_emociones_Y_tareas/",
    prRepoitory: "https://github.com/CrisCaBeRi/Semillas_emociones_Y_tareas.git",
  },
  {
    prItem: 5,
    prImg: "https://drive.google.com/uc?export=view&id=1UZzkeWRhhYx9rvHwTbuIog0RQuk-80op",
    prTitle: "Tetris JS",
    prDescription: "Videojuego introductorio, replica del clásico tetris, para la aproximación a la programación & animación web utilizando Javascript y Canvas con las bases de detección de colisiones.",
    prTechnologies: ["html", "css", "js"],    
    prDeploy: "https://criscaberi.github.io/Programate_Academy_TETRIS/",
    prRepoitory: "https://github.com/CrisCaBeRi/Programate_Academy_TETRIS.git",
  },
  {
    prItem: 6,
    prImg: "https://drive.google.com/uc?export=view&id=1VkD7YYDZ33HGnBcimmGLlhIfSmgSgNHK",
    prTitle: "Dashboard Crypto",
    prDescription: "Desarrollo de un dashboard utilizando REACT y haciendo el consumo de una API sobre criptomonedas. En este dashboard se pueden filtrar históricos de estadística frente a valores de varias monedas en cuanto a perdida o ganancia de valor.",
    prTechnologies: ["html", "css", "js", "react"],
    prDeploy: "https://criscaberi.github.io/DashboardCrypto/",    
    prRepoitory: "https://github.com/CrisCaBeRi/DashboardCrypto.git"    
  },
  {
    prItem: 7,
    prImg: "https://drive.google.com/uc?export=view&id=11rtV2oqR-eNFX4pW1W-6W0X5QSdex5lv",
    prTitle: "Angel's Makeup",
    prDescription: "Proyecto de tienda virtual tipo E-Commerce de venta de insumos de belleza para cliente real utilizando REACT. En este desarrollo se implementan los principios de diseño y librerías externas como REACT - REDUX para el manejo de estados globales.",
    prTechnologies: ["html", "css", "js", "react"],
    prDeploy: "https://angels-make-up.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/angelsMakeUp.git",
  }, 
  {
    prItem: 8,
    prImg: "https://drive.google.com/uc?export=view&id=1bT1iNJQdDI9f6-Y7eBa3v9TnsWG5XNRn",
    prTitle: "Cadencia BTS Design",
    prDescription: "Caso práctico desarrollado para el curso de UX Design de Google. Este proyecto consiste en el diseño de una aplicación que permita la conexión de los usuarios con los servicios de mecánica de bicicletas utilizando los estándares de accesibilidad y usabilidad.",
    prTechnologies: ["Figma", "Illustrator"],
    prDeploy: "https://www.figma.com/file/Kxudfg0nsJLGLdDK22Gk75/Google-UX-Mockup?node-id=46%3A17&t=HeProhuefWcTXQ41-1",
    prRepoitory: "https://drive.google.com/file/d/1eTwg28fpn8-uHJ69C48pEHr5mFTaKFWA/view?usp=sharing",
  }, 
  {
    prItem: 9,
    prImg: "https://drive.google.com/uc?export=view&id=1AprsIEAVxyIVXd5ksY24i19GQtoDq9pe",
    prTitle: "Cadencia BTS Design for mechanics",
    prDescription: "Caso práctico desarrollado para el curso de UX Design de Google. Este proyecto se basa en el diseño de una aplicación o aplicativo web que permita a los mecánicos de bicicletas hacer la gestión de su trabajo de una manera más eficaz, agregando diferentes funcionalidades que le permitan llevar una comunicación más directa y técnica con sus clientes, todo esto basándose en los estándares de accesibilidad y usabilidad requeridos.",
    prTechnologies: ["Adobe XD", "Illustrator"],
    prDeploy: "https://xd.adobe.com/view/8662f3e8-6ca2-4c48-ae0a-4e42bbe8acee-d331/",
    prRepoitory: "https://drive.google.com/file/d/1Nd96MggOsJbgUVy0uUmWiTeOKQZJawvU/view?usp=sharing",
  }, 
  {
    prItem: 10,
    prImg: " https://drive.google.com/uc?export=view&id=1TTeC-iXcUyez0d4OVpyfCrDfV9QQwdFo",
    prTitle: "LegalApp Design",
    prDescription: "Caso práctico desarrollado para el curso de UX Design de Google implementando diseño de aplicación dedicada y web responsive. En este proyecto se toma una iniciativa de interés público para desarrollar un diseño en el cual se suplan las necesidades de la sociedad frente a la falta de socialización de políticas y la perdida de interés por estas utilizando herramientas para incentivar la capacitación por medio de estándares de accesibilidad y usabilidad.",
    prTechnologies: ["Figma", "Illustrator"],
    prDeploy: "https://www.figma.com/file/GJ1yJkZm1aYNVWVLkDn0hR/GOOGLE-UX-LwFi-Prototype-LegislAPP?node-id=0%3A1&t=6BbeX6Hc3ZpNMhzO-1",
    prRepoitory: "https://drive.google.com/file/d/1XTBrpSANAvwRX71uHA2V0vT_D582mAZ1/view?usp=share_link",
  }, 
  {
    prItem: 11,
    prImg: "https://drive.google.com/uc?export=view&id=1V6eD_JEpzzUDUZpJLg3YlyupK29gGZdI",
    prTitle: "Reply Deezer",
    prDescription: "Proyecto de aprendizaje sobre maquetación web, replicando la plataforma web de Deezer utilizando únicamente HTML5 y CSS vanilla.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://deezer1.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/DEEZER-.git",
  }, 
  {
    prItem: 12,
    prImg: "https://drive.google.com/uc?export=view&id=1FLHAI-tw84g22l_2elWKdfPWSyc1q67O",
    prTitle: "Todo List Tambo Flowers",
    prDescription: "Desarrollo web introductorio al backend y al patrón de arquitectura MVC (modelo - vista - controlador) por medio del entorno de Node JS, Express JS y manejo de bases de datos no relacionales utilizando Mongo DB.",
    prTechnologies: ["html", "css", "js", "react", "NodeJS", "Mongo DB"],
    prDeploy: "https://todolist-tambo-flowers-front.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/todolist-tambo-flowers.git",
  }, 
  {
    prItem: 13,
    prImg: "https://drive.google.com/uc?export=view&id=1y15btVyisvACPMROZ0khW-nQj1lpmNgV",
    prTitle: "ARFOS App móvil de control de pedidos ",
    prDescription: "Desarrollo de aplicación móvil en Android Studio utilizando el lenguaje de programación Dart y el SDK de Flutter. Incluyendo servicios de Firebase para bases de datos, autenticación y demás servicios.",
    prTechnologies: ["Dart", "Firebase" ],
    prDeploy: "https://www.figma.com/file/2nTz3ZdXhP77ysBAdntFgj/ARFOS?node-id=0%3A1&t=SWe6yADQJj7vwQDu-1",
    prRepoitory: "https://gitlab.com/pmurciavilla/app-mobil-demo/-/tree/Cristian?ref_type=heads",
  },
  {
    prItem: 14,
    prImg: "https://drive.google.com/uc?export=view&id=1uu10ChPcL6RiOkPUYSnnDBKBAZGsu7kN",
    prTitle: "Wheel of Zombies",
    prDescription: "Videojuego temático de Zombies desarrollado utilizando HTML5, CSS y Javascript, basándose en el uso de Canvas con las bases de detección de colisiones y uso de eventos característicos de JS.",
    prTechnologies: ["html", "css", "js"],
    prDeploy: "https://lambent-axolotl-7d7967.netlify.app/",
    prRepoitory: "https://gitlab.com/prueba776/prueba-proyecto.git",
  },
  {
    prItem: 15,
    prImg: "https://drive.google.com/uc?export=view&id=1GEIvTSZ1_PVk7qAYdNuROWXrECTtgk_Q",
    prTitle: "Sinergias Alianzas Estratégicas",
    prDescription: "Proyecto real en fase 1 de la fundación Sinergias Alianzas Estratégicas para la salud y el desarrollo social. En este proyecto se desarrollaron los módulos de autenticación y gestión de cursos ofrecidos utilizando el stack de MERN y librerías adicionales como REDUX.",
    prTechnologies: ["html", "css", "js", "react", "Node Js","Mongo DB"],
    prDeploy: "https://www.figma.com/file/ZimeF9HKufurfqWePNAx1F/Sinergias-Alianzas-Estrat%C3%A9gicas-para-la-salud-y-el-desarrollo-social?node-id=0%3A1&t=pGliLHWyYbs9zOQw-1",
    prRepoitory: "https://github.com/CrisCaBeRi/4-Sinergias-Alianzas-Front-end.git",
  },
  {
    prItem: 16,
    prImg: "https://drive.google.com/uc?export=view&id=1Ap6D04JFQRwDFn3Jc8ZiXx1CyRizc0bv",
    prTitle: "Devflix",
    prDescription: "CRUD basado en un servicio de streaming de películas antiguas que contiene información específica de cada una, utilizando el stack de MERN e incluyendo autenticación de usuarios.",
    prTechnologies: ["html", "css", "js", "react", "Node Js","Mongo DB"],
    prDeploy: "https://dev-flix-front.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/DevFlix-MERN.git",
  },
  {
    prItem: 17,
    prImg: "https://drive.google.com/uc?export=view&id=1LcO-nsu2RwS-oR7W9tUN68d3GOmyNDmC",
    prTitle: "Cadencia BTS Landing Page",
    prDescription: "Landing page realizada para Cadencia Bike Technical Service, en ésta, se pueden encontrar elementos de diseño en 3d y 2d realizados con herramientas como Blender, Illustrator y Animate.",
    prTechnologies: ["html", "css"],
    prDeploy: "https://cadencia-landing.vercel.app/",
    prRepoitory: "https://github.com/CrisCaBeRi/Cadencia_Landing.git",
  }
];
